"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""


# The command we've used to compile this application is:
# python setup-py2app.py py2app -p "jaide,Pmw,paramiko,ncclient" -i "scp"

from setuptools import setup

APP = ['jaidegui/Jaide GUI.py']
DATA_FILES = []
OPTIONS = {'argv_emulation': True}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
    install_requires=[
        # 'jaide>=2.0.0',
        'Pmw>=1.3.3'
    ],
)
