site_name: Jaide GUI
site_author: Nathan Printz
site_description: Jaide GUI for manipulating Junos Devices
repo_url: https://github.com/NetworkAutomation/jaidegui
pages:
    - ['index.md', 'Home']
    - ['about.md', 'About Us']
    - ['description.md', 'Jaide Basic Description']
    - ['which-is-for-me.md', 'Jaide vs the CLI tool vs the GUI']
    - ['installation.md', 'Installation and Requirements']
    - ['usage.md', 'Basic Usage']
    - ['version-history.md', 'Version History']
    # - ['examples/cli/authentication.md', 'CLI Examples', 'Authenticating and Connecting']
    # - ['examples/cli/get-device-info.md', 'CLI Examples', 'Basic Device Information']
    # - ['examples/cli/checking-interface-errors.md', 'CLI Examples', 'Checking Interface Errors']
    # - ['examples/cli/making-commits.md', 'CLI Examples', 'Commit Changes']
    # - ['examples/cli/diff-config.md', 'CLI Examples', 'Compare Differences with Another Device']
    # - ['examples/cli/scp-files-and-folders.md', 'CLI Examples', 'Copying Files']
    # - ['examples/cli/getting-health-checks.md', 'CLI Examples', 'Health Checks']
    # - ['examples/cli/operational-commands.md', 'CLI Examples', 'Operational Commands']
    # - ['examples/cli/shell-commands.md', 'CLI Examples', 'Shell Commands']
    # - ['examples/cli/show-compare.md', 'CLI Examples', 'Show | Compare Set Commands']
    # - ['examples/cli/custom-timeout.md', 'CLI Examples', 'Specifying Custom Timeouts']
    # - ['examples/cli/working-with-many-devices.md', 'CLI Examples', 'Working with Multiple Devices']
    # - ['examples/cli/writing-output-to-file.md', 'CLI Examples', 'Writing Output to File(s)']
    # - ['examples/lib/examples.md', 'Jaide Class Examples', 'Working with the Jaide class']
    # - ['api/api.md', 'API Reference']
theme: readthedocs
