site_name: Jaide GUI
site_author: Nathan Printz
site_description: Jaide GUI for manipulating Junos Devices
repo_url: https://github.com/NetworkAutomation/jaidegui
pages:
    - ['index.md', 'Home']
    - ['description.md', 'Jaide Basic Description']
    - ['which-is-for-me.md', 'Jaide vs the CLI tool vs the GUI']
    - ['installation.md', 'Installation and Requirements']
    - ['usage.md', 'Basic Usage']
    - ['about.md', 'About Us']
    - ['version-history.md', 'Version History']
theme: readthedocs
